name: Deploy static site to S3

# uruchamiaj przy pushu do main i manualnie
on:
  push:
    branches:
      - main            # jeśli Twoja główna gałąź to 'master', zamień na master
    paths:
      - 'frontend/index.html'
      - 'frontend/script.js'
      - 'frontend/style.css'
      - 'frontend/assets/**'  # jeśli masz katalog assets
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Sync to S3 bucket
        run: |
          aws s3 sync frontend/ s3://${{ secrets.S3_BUCKET }} \
            --exclude ".git/*" \
            --delete
